### ISSUE TITLE
cache

### ISSUE THREAD

**Issue by srakl** [thamtech/yii2-ratelimiter-advanced#8]
here is my setting

```
'rateLimit' => [
                'definitions' => [
                    'ip' => [
                        'limit' => 1000, // allowed hits per window
                        'window' => 3600, // window in seconds
                        'identifier' => function($context, $rateLimitId) {
                            return $context->request->getUserIP();
                        }
                    ],
                ],
            ],
'allowanceStorage' => [
    'cache' => [
        'class' => 'yii\caching\DbCache',
        'cacheTable' => 'cacheTable',
    ],
]
```

here is my cache table

```
CREATE TABLE cacheTable (
    id char(128) NOT NULL PRIMARY KEY,
    expire int(11),
    data BLOB
);
```

when i run it, i get this error

```Calling unknown method: yii\caching\DbCache::loadAllowance()```

Any idea what i missed? Thanks

**Comment by tyler-ham** [comment]
I can't tell from the snippets you provided. Can you provide a stack trace and a more complete example of your config and code?

You've shown this config in your post:

```php
'allowanceStorage' => [
    'cache' => [
        'class' => 'yii\caching\DbCache',
        'cacheTable' => 'cacheTable',
    ],
]
```

`loadAllowance()` is a method of `AllowanceCacheStorage.php` (and its interface definition, `AllowanceStorageInterface.php`), and is only ever called on the `allowanceStorage` object. Your error indicates that something is attempting to call `loadAllowance()` on a `DbCache` object instead. So I wonder, is it possible that there is a typo in your code that has led to `'class' => 'yii\caching\DbCache'` being specified under `allowanceStorage` instead of `allowanceStorage -> cache`?

**Comment by srakl** [comment]
here is my full `behaviors()`

```
public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['rateLimiter'] = [
            'class' => 'thamtech\ratelimiter\RateLimiter',
            'components' => [
                'rateLimit' => [
                    'definitions' => [
                        'ip' => [
                            'limit' => 100, // allowed hits per window
                            'window' => 900, // window in seconds (15 min)
                            'identifier' => function($context, $rateLimitId) {
                                return $context->request->getUserIP();
                            }
                        ],
                    ],
                ],
                'allowanceStorage' => [
                    'class' => 'yii\caching\DbCache',
                    'cacheTable' => 'cacheTable'
                ],
            ],
            'as rateLimitHeaders' => [
                'class' => 'thamtech\ratelimiter\handlers\RateLimitHeadersHandler',
                'prefix' => ['X-Rate-Limit-', 'X-RateLimit-'],
            ],
            'as retryAfterHeader' => 'thamtech\ratelimiter\handlers\RateLimitHeadersHandler',
            'as tooManyRequestsException' => 'thamtech\ratelimiter\handlers\TooManyRequestsHttpExceptionHandler',
        ];
        return $behaviors;
    }
```

and here the full trace

```
2023-05-24 00:39:15 [127.0.0.1][-][d87034df603d79a256f088c617e20331][error][yii\base\UnknownMethodException] yii\base\UnknownMethodException: Calling unknown method: yii\caching\DbCache::loadAllowance() in C:\MAMP\htdocs\blabla-yii2\vendor\yiisoft\yii2\base\Component.php:300
Stack trace:
#0 C:\MAMP\htdocs\blabla-yii2\vendor\thamtech\yii2-ratelimiter-advanced\src\RateLimiterComponent.php(154): yii\base\Component->__call('loadAllowance', Array)
#1 C:\MAMP\htdocs\blabla-yii2\vendor\thamtech\yii2-ratelimiter-advanced\src\RateLimiterComponent.php(203): thamtech\ratelimiter\RateLimiterComponent->checkRateLimit(Object(thamtech\ratelimiter\limit\RateLimit), Object(thamtech\ratelimiter\Context), 'ip')
#2 C:\MAMP\htdocs\blabla-yii2\vendor\thamtech\yii2-ratelimiter-advanced\src\RateLimiterComponent.php(98): thamtech\ratelimiter\RateLimiterComponent->checkRateLimits(Array, Object(thamtech\ratelimiter\Context))
#3 C:\MAMP\htdocs\blabla-yii2\vendor\thamtech\yii2-ratelimiter-advanced\src\RateLimiter.php(93): thamtech\ratelimiter\RateLimiterComponent->beforeAction(Object(frontend\modules\calculator\controllers\actions\roadtaxCalculatorAction))
#4 C:\MAMP\htdocs\blabla-yii2\vendor\yiisoft\yii2\base\ActionFilter.php(77): thamtech\ratelimiter\RateLimiter->beforeAction(Object(frontend\modules\calculator\controllers\actions\roadtaxCalculatorAction))
#5 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))
#6 C:\MAMP\htdocs\blabla-yii2\vendor\yiisoft\yii2\base\Component.php(633): call_user_func(Array, Object(yii\base\ActionEvent))
#7 C:\MAMP\htdocs\blabla-yii2\vendor\yiisoft\yii2\base\Controller.php(297): yii\base\Component->trigger('beforeAction', Object(yii\base\ActionEvent))
#8 C:\MAMP\htdocs\blabla-yii2\vendor\yiisoft\yii2\web\Controller.php(222): yii\base\Controller->beforeAction(Object(frontend\modules\calculator\controllers\actions\roadtaxCalculatorAction))
#9 C:\MAMP\htdocs\blabla-yii2\vendor\yiisoft\yii2\base\Controller.php(176): yii\web\Controller->beforeAction(Object(frontend\modules\calculator\controllers\actions\roadtaxCalculatorAction))
#10 C:\MAMP\htdocs\blabla-yii2\vendor\yiisoft\yii2\base\Module.php(552): yii\base\Controller->runAction('roadtax-calcula...', Array)
#11 C:\MAMP\htdocs\blabla-yii2\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('calculator/defa...', Array)
#12 C:\MAMP\htdocs\blabla-yii2\vendor\yiisoft\yii2\base\Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#13 C:\MAMP\htdocs\blabla-yii2\frontend\web\index.php(79): yii\base\Application->run()
#14 {main}
```

**Comment by srakl** [comment]
Thank you, solved. was a missing bracket thanks to late night coding.

Can i use the same cache table used for my website? or should i have a separate one for the rate limiter?

**Comment by tyler-ham** [comment]
It's up to you. If you use the same underlying cache table, I recommend using the same cache component as your application rather than redefining a separate `DbCache` instance.

For example, if the component ID of your application's cache component is `cache`, you can specify that ID as allowanceStorage's cache property:

```php
'allowanceStorage' => [
    // allowanceStorage 'cache' property => component ID of your application's cache component
    'cache' => 'cache',
]
```

The default `allowanceStorage` is an instance of `AllowanceCacheStorage`. And by default, it prefixes all of the cache keys it uses with its fully-qualified class name and a configurable cache key prefix. This prefix is set in the `cacheKeyPrefix` property of `AllowanceCacheStorage` and defaults to `allowance`. All that is to say that, by default, the cache entries should already be well-scoped to avoid any collisions with any entries the rest of your application makes. And if not, you can always set the `cacheKeyPrefix` to something unique if you need to.
